# Generated by Django 2.0.7 on 2018-07-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larricia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
